from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from app.scripts.extract_kb_source_manifest import repo_root


def read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Required file not found: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def markdown_escape(value: Any) -> str:
    text = "UNKNOWN" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", " ")


def render_summary(draft: dict[str, Any]) -> str:
    diagnostics = draft.get("diagnostics", {})
    policy = draft.get("generation_policy", {})
    lines: list[str] = []
    lines.append("# KB Impact Draft Summary")
    lines.append("")
    lines.append(f"Generated UTC: `{draft.get('generated_utc', '')}`")
    lines.append("")
    lines.append("## Overview")
    lines.append("")
    lines.append(f"- Artifact type: `{draft.get('artifact_type', '')}`")
    lines.append(f"- Schema version: `{draft.get('schema_version', '')}`")
    lines.append(f"- Draft status: `{draft.get('draft_status', '')}`")
    lines.append(f"- Draft sections: {diagnostics.get('draft_sections', 0)}")
    lines.append(f"- Draft claims: {diagnostics.get('draft_claims', 0)}")
    lines.append(f"- Evidence citation count: {diagnostics.get('evidence_citation_count', 0)}")
    lines.append(f"- Unresolved gaps: {diagnostics.get('unresolved_gap_count', 0)}")
    lines.append(f"- Image-bearing cited evidence: {diagnostics.get('image_bearing_cited_evidence', 0)}")
    lines.append("")
    lines.append("## Generation Policy")
    lines.append("")
    for key, value in sorted(policy.items()):
        lines.append(f"- {key}: `{value}`")
    lines.append("")
    lines.append("## Interpretation")
    lines.append("")
    lines.append(
        "This is a constrained, citation-bound draft generated by deterministic templates from the enriched evidence context. "
        "It is not reviewed, not final, and not a business conclusion. Evidence-backed claims include evidence IDs."
    )
    lines.append("")

    lines.append("## Draft Sections")
    lines.append("")
    lines.append("| Section | Status | Claims | Unresolved Gaps |")
    lines.append("|---|---|---:|---:|")
    for section in draft.get("sections", []):
        lines.append(
            "| "
            f"{markdown_escape(section.get('title'))} | "
            f"{markdown_escape(section.get('status'))} | "
            f"{len(section.get('claims') or [])} | "
            f"{len(section.get('unresolved_gaps') or [])} |"
        )
    lines.append("")

    lines.append("## Claims")
    lines.append("")
    for section in draft.get("sections", []):
        claims = section.get("claims") or []
        if not claims:
            continue
        lines.append(f"### {section.get('title')}")
        lines.append("")
        for claim in claims:
            lines.append(f"- `{claim.get('claim_id')}` ({claim.get('claim_type')}): {claim.get('text')}")
            if claim.get("caveats"):
                for caveat in claim.get("caveats"):
                    lines.append(f"  - Caveat: {caveat}")
        lines.append("")

    unresolved_sections = [section for section in draft.get("sections", []) if section.get("unresolved_gaps")]
    if unresolved_sections:
        lines.append("## Unresolved Evidence Gaps")
        lines.append("")
        for section in unresolved_sections:
            for gap in section.get("unresolved_gaps") or []:
                lines.append(f"- {gap}")
        lines.append("")

    lines.append("## Source Inputs")
    lines.append("")
    lines.append(f"- Source context: `{draft.get('source_context_path', '')}`")
    lines.append(f"- Source skeleton: `{draft.get('source_skeleton_path', '')}`")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    root = repo_root()
    parser = argparse.ArgumentParser(description="Write reviewer-facing Gate 8 impact draft summary.")
    parser.add_argument("--draft", type=Path, default=root / "kbs" / "impact_context" / "kb_impact_draft.v1.json")
    parser.add_argument("--output", type=Path, default=root / "kbs" / "manifests" / "kb_impact_draft_summary.md")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    draft = read_json(args.draft)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_summary(draft), encoding="utf-8")
    diagnostics = draft.get("diagnostics", {})
    print(f"Wrote KB impact draft summary: {args.output}")
    print(f"Draft sections: {diagnostics.get('draft_sections', 0)}")
    print(f"Draft claims: {diagnostics.get('draft_claims', 0)}")
    print(f"Unresolved gaps: {diagnostics.get('unresolved_gap_count', 0)}")


if __name__ == "__main__":
    main()
