from enum import StrEnum


class AnalysisStatus(StrEnum):
    DRAFT = "DRAFT"
    INTAKE_VALIDATED = "INTAKE_VALIDATED"
    ANALYSIS_RUNNING = "ANALYSIS_RUNNING"
    ANALYSIS_COMPLETE = "ANALYSIS_COMPLETE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    READY = "READY"
    ARCHIVED = "ARCHIVED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    STALE = "STALE"
    REQUIRES_REFRESH = "REQUIRES_REFRESH"


class FindingStatus(StrEnum):
    OPEN = "OPEN"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    RESOLVED = "RESOLVED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class ReviewStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    COMPLETED = "COMPLETED"


class ChangeTaxonomy(StrEnum):
    FEATURE_CHANGE = "FEATURE_CHANGE"
    CONFIGURATION_CHANGE = "CONFIGURATION_CHANGE"
    SCHEMA_CHANGE = "SCHEMA_CHANGE"
    INTEGRATION_CHANGE = "INTEGRATION_CHANGE"
    SECURITY_CHANGE = "SECURITY_CHANGE"
    REPORTING_CHANGE = "REPORTING_CHANGE"
    PROCESS_CHANGE = "PROCESS_CHANGE"
    DEPRECATION = "DEPRECATION"
    BUG_FIX = "BUG_FIX"
    OTHER = "OTHER"


class Severity(StrEnum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ImpactType(StrEnum):
    NONE = "NONE"
    FUNCTIONAL = "FUNCTIONAL"
    TECHNICAL = "TECHNICAL"
    OPERATIONAL = "OPERATIONAL"
    DATA = "DATA"
    SECURITY = "SECURITY"
    COMPLIANCE = "COMPLIANCE"
    PERFORMANCE = "PERFORMANCE"
    INTEGRATION = "INTEGRATION"


class EnvironmentType(StrEnum):
    DEV = "DEV"
    TEST = "TEST"
    PROD = "PROD"


class ReviewItemStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    DEFERRED = "DEFERRED"


class CustomerEnvironmentType(StrEnum):
    PRODUCTION = "PRODUCTION"
    TEST = "TEST"
    DEVELOPMENT = "DEVELOPMENT"


class ChangeClassification(StrEnum):
    CONFIGURATION = "CONFIGURATION"
    BEHAVIORAL = "BEHAVIORAL"
    SCHEMA = "SCHEMA"
    INTEGRATION = "INTEGRATION"
    SECURITY = "SECURITY"
    PERFORMANCE = "PERFORMANCE"
    DEPRECATION = "DEPRECATION"
    REPORTING = "REPORTING"
    WORKFLOW = "WORKFLOW"
    UI = "UI"
    DOCUMENTATION = "DOCUMENTATION"


class ReportStatus(StrEnum):
    APPLIES = "APPLIES"
    DOES_NOT_APPLY = "DOES_NOT_APPLY"
    POSSIBLE_MATCH = "POSSIBLE_MATCH"
    UNKNOWN = "UNKNOWN"
    BLOCKED = "BLOCKED"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"


class CustomizationObjectType(StrEnum):
    WORKFLOW = "WORKFLOW"
    REPORT = "REPORT"
    SCRIPT = "SCRIPT"
    EXTENSION = "EXTENSION"
    DATABASE_OBJECT = "DATABASE_OBJECT"


class IntegrationInterfaceType(StrEnum):
    API = "API"
    BATCH = "BATCH"
    FILE = "FILE"
    MESSAGE_QUEUE = "MESSAGE_QUEUE"


class CriticalityLevel(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class JobType(StrEnum):
    BATCH = "BATCH"
    REPORT = "REPORT"
    SCHEDULED_TASK = "SCHEDULED_TASK"